name: Deploy MultiDocker
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t sachinarya/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true sachinarya/react-test npm test

      - run: docker build -t sachinarya/multi-client ./client
      - run: docker build -t sachinarya/multi-nginx ./nginx
      - run: docker build -t sachinarya/multi-server ./server
      - run: docker build -t sachinarya/multi-worker ./worker

      - run: docker push sachinarya/multi-client
      - run: docker push sachinarya/multi-nginx
      - run: docker push sachinarya/multi-server
      - run: docker push sachinarya/multi-worker